version: '3'
services:

  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    ports:
      - "5432:5432"
    volumes:
      - /var/log/nginx:/var/log/nginx
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./data/nginx/mime.type:/etc/nginx/mime.type
      - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
      - db-network
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13.5
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres/database:/var/lib/postgresql/data
      - ./data/postgres/config:/root/config
      - ./data/postgres/certs/server.crt:/var/lib/postgresql/server.crt
      - ./data/postgres/certs/server.key:/var/lib/postgresql/server.key
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    networks:
      - db-network

  node_exporter:
    image: prom/node-exporter:v1.3.1
    container_name: node_exporter
    restart: always
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100



networks:
  db-network:
