version: '3'
services:

  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    ports:
      - "5432:5432"
    volumes:
      - /var/log/nginx:/var/log/nginx
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./data/nginx/mime.type:/etc/nginx/mime.type
      - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
      - db-network
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      #PGDATA: /etc/data
    volumes:
      - ./data/postgres/database:/var/lib/postgresql/data
      - ./data/postgres/config:/root/config
      - ./data/postgres/certs/server.crt:/var/lib/postgresql/server.crt
      - ./data/postgres/certs/server.key:/var/lib/postgresql/server.key
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    networks:
      - db-network


networks:
  db-network:
