version: '3'
services:

#  nginx:
#    container_name: nginx
#    image: nginx:1.15-alpine
#    ports:
#      - "5432:5432"
#    volumes:
#      - /var/log/nginx:/var/log/nginx
#      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./data/nginx/proxy.conf:/etc/nginx/proxy.conf
#      - ./data/nginx/mime.type:/etc/nginx/mime.type
#      - /etc/letsencrypt/:/etc/letsencrypt/
#    networks:
#      - db-network
#    depends_on:
#      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./data/postgres/database:/var/lib/postgresql/data
      - ./data/postgres/config:/root/config
    networks:
      - db-network


networks:
  db-network:
