@startuml deployment
/' NOT FINAL '/
actor alice as a
frame "Application server" {

  node  Docker #aliceblue;line:blue;line.dotted;text:blue
  node node_exporter
  frame "Docker app-network" {
    node Nginx
    node MiniTwit
  }

a -> Docker : ":443"
a -> Docker : ":9100"
Docker-> Nginx : ":443"
Nginx -> MiniTwit: ":80"
Docker-> node_exporter : ":9100"
}

frame "Database server" {

  node Docker2 #aliceblue;line:blue;line.dotted;text:blue
  node node_exporter2
    database ./data/postgres/data as db {
     /' storage MiniTwit_db '/
    }

  frame "Docker db-network" as dockernet  {
    node Nginx2
    node Postgres

}


a -> Docker2 : ":9100"
Nginx2 -> Postgres : ":5432"
MiniTwit -> Docker2 : ":5432"
Docker2 -> Nginx2 : ":5432"
Docker2 -> node_exporter2 : ":9100"
Postgres -- db
}

frame "Monitoring server" {

  node  Docker3 #aliceblue;line:blue;line.dotted;text:blue
  frame "Docker monitoring-network" {
    node Nginx3
    node node_exporter3
    node prometheus
    node grafana
    node loki
    node data_scraper
  }

  /'
  folder "/etc/letsencrypt/live/thomsen-it.dk" as certs {
    file "cert.pem"
    file "chain.pem"
    file "fullchain.pem"
    file "privkey.pem"
  }

  folder "/var/logs/" as logs {
    folder "Nginx" as NginxLog {
      file "access.log"
      file "thomsen-it.access.log"
    }
  }

  folder "/etc/loki/config" as lokifolder {
    file "loki.yaml"
  }

  folder "/etc/prometheus/config" as prometheusfolder {
    file "prometheus.yaml"
  }

  folder "/etc/grafana/" as grafanafolder {
    folder "provisioning" as grafanaprovisioning {
      folder "dashboards"
      folder "datasources"
      folder "notifiers"
    }
    folder "dashboards" as grafanadashboards {
      file "NodeExporter.json"
      folder "Minitwit" as grafanadashboardsminitwit {
      file "Alerts.json"
      file "Endpoint.json"
      file "Heatmaps.json"
      file "Minitwit.json"
      file "Simulator.json"
    }
    }
  } '/

a -> Docker3 : ":80"
a -> Docker3 : ":443"
a -> Docker3 : ":3100"
a -> Docker3 : ":9090" 
a -> Docker3 : ":9100"

Docker3 -> Nginx3 : ":80, :443, :3100 and :9090"



/' Docker -> node_exporter : ":9100" '/

prometheus -> node_exporter3 #line:red;text:red : ":9100"
prometheus -> data_scraper : ":8080"
prometheus -> prometheus : ":9090" /' Maybe not important? '/
/' prometheus -> node_exporter (the other 2 servers) : ":9100" '/
/' prometheus -> minitwit (thomsen-it.dk) : ":9100" '/


Nginx3 -> grafana #line:green;text:green : ":3000"
Nginx3 -> loki #line:blue;text:blue :":3100"
Nginx3 -> prometheus : ":9090"



/'
Nginx -- certs
Nginx -- NginxLog
grafana -- grafanafolder
prometheus -- prometheusfolder
loki -- lokifolder'/

}



@enduml