version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx/logs/:/var/log/nginx
      - ./data/nginx:/etc/nginx/conf.d
      - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
      - app-network

networks:
  app-network: