version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/log/nginx:/var/log/nginx
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./data/nginx/mime.type:/etc/nginx/mime.type
      - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
      - app-network
    depends_on:
      - minitwit1

  minitwit1:
    container_name: minitwit1
    image: groupddevops/minitwit-go:latest
    restart: always
    environment:
      - SERVER_HOST=thomsen-it.dk
      - DB_CONNECTION_STRING=/tmp/minitwit.db
    volumes:
      - ./data/minitwit/:/tmp/
    networks:
      - app-network


networks:
  app-network:
