@startuml deployment
actor alice as a
/'cloud MonitorServer as MS '/
frame "Application server" {

  node node_exporter

  node Docker #aliceblue;line:blue;line.dotted;text:blue

  frame "Docker app-network" {
    node Nginx
    node fluentd /' Not really in the network, but makes the drawing nicer '/
    node MiniTwit
  }

  folder "/etc/letsencrypt/live/thomsen-it.dk" as certs {
    file "cert.pem"
    file "chain.pem"
    file "fullchain.pem"
    file "privkey.pem"
  }

  folder "/var/logs/" as logs {
    folder "Nginx" as NginxLog {
      file "access.log"
      file "thomsen-it.access.log"
    }
    folder "Minitwit" as miniTwitLogs {
      file "minitwit.log" 
    }
  }

a -> Docker : ":443 and :9100"

Docker-> Nginx : ":443"
Docker-> node_exporter : ":9100"
Nginx -> MiniTwit: ":80"

MiniTwit -> fluentd: ":24224"
Nginx -> fluentd: ":24224"

/'MS -> Docker : ":9100" 
fluentd -> MS'/

Nginx -- certs
Nginx -- NginxLog
MiniTwit -- miniTwitLogs
}
@enduml