version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/log/nginx:/var/log/nginx
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./data/nginx/mime.type:/etc/nginx/mime.type
      - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
      - app-network
    depends_on:
      - minitwit
      - fluentbit
    logging:
      driver: fluentd
      options:
        tag: docker.{{.Name}}

  minitwit:
    container_name: minitwit
    image: groupddevops/minitwit-go:393f2bd
    restart: always
    environment:
      - SERVER_HOST=thomsen-it.dk
      - DB_TYPE=Postgres
      - DB_CONNECTION_STRING=${CONNECTION_STRING}
    networks:
      - app-network
    depends_on:
      - fluentbit
    logging:
      driver: fluentd
      options:
        tag: docker.{{.Name}}

  fluentbit:
    image: fluent/fluent-bit:1.9.0
    container_name: fluentbit
    restart: always
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./data/fluentbit/config/:/fluent-bit/etc/

  node_exporter:
    image: prom/node-exporter:v1.3.1
    container_name: node_exporter
    restart: always
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100


networks:
  app-network:
